## DataSet Information 

Dimasalah ini kamu tidak perlu memprediksi harga aktualnya tetapi indicator rentang harganya.

##### Ini adalah masalah standart Superviced Classification. Sebuah masalah dimana kita harus memprediksi rentang harga dari mobile dari 0 (low cost), 1(medium), 2(high), 3(very high)


#### Dibawah ini adalah atribut datasetnya beserta deskripsinya
| Column | Description |
| --- | --- |
| battery_power |  Total energy a battery can store in one time measured in mAh |
| blue |  Has bluetooth or not |
| clock_speed |  speed at which microprocessor executes instructions |
| dual_sim |  Has dual sim support or not |
| fc |  Front Camera mega pixels |
| four_g |  Has 4G or not |
| int_memory |  Internal Memory in Gigabytes |
| m_dep |  Mobile Depth in cm |
| mobile_wt |  Weight of mobile phone |
| n_cores |  Number of cores of processor |
| pc |  Primary Camera mega pixels |
| px_height |  Pixel Resolution Height |
| px_width |  Pixel Resolution Width |
| ram |  Random Access Memory in Mega Bytes |
| sc_h |  Screen Height of mobile in cm |
| sc_w |  Screen Width of mobile in cm |
| talk_time |  longest time that a single battery charge will last when you are |
| three_g |  Has 3G or not |
| touch_screen |  Has touch screen or not |
| wifi |  Has wifi or not |
| price_range |  This is the target variable with value of 0(low cost), 1(medium cost), 2(high cost) and 3(very high cost).|
     
     Sumber dataset ini adalah Kaggle.com.
   
  Source : https://www.kaggle.com/iabhishekofficial/mobile-price-classification?select=train.csv



## Preprocessing

#### Import Library & Memuat dataset

In [44]:
# Mengimpor pustaka yang diperlukan
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from imblearn.over_sampling import RandomOverSampler
from sklearn.decomposition import PCA
from sklearn.neighbors import RadiusNeighborsClassifier
from sklearn.metrics import accuracy_score

#Load dataset
df = pd.read_csv('train.csv')




#### Memilih fitur

In [45]:
X = df.drop(['price_range'], axis=1) 
y = df['price_range']

#### Menangani Missing Value

In [46]:
missing_values = df.isnull().sum()
print(missing_values)

battery_power    0
blue             0
clock_speed      0
dual_sim         0
fc               0
four_g           0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
three_g          0
touch_screen     0
wifi             0
price_range      0
dtype: int64


#### Menghapus Data yang tidak relevan

#### Mengubah Data kategorikal menjadi numerik

In [47]:
label_encoder = LabelEncoder()
for column in X.columns:
    if X[column].dtype == 'object':
        X[column] = label_encoder.fit_transform(X[column])

#### Menormalisasi atau mengubah skala data

In [48]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

#### Memisihakan Data menjadi set pelatihan dan pengujian

In [49]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

#### Menangani data yang tidak seimbang (oversampling)

In [50]:
ros = RandomOverSampler(random_state=50)
X_train_resampled, y_train_resampled = ros.fit_resample(X_train, y_train)

#### Menjalankan normalisasi dengan menghilangkan outlier atau mengurangi dimensi data (PCA)

In [51]:
# pca = PCA(n_components=2)
# X_train_pca = pca.fit_transform(X_train_resampled)
# X_test_pca = pca.transform(X_test)

## Evaluasi Model

#### Inisialisasi dan melatih model

In [52]:
model = RadiusNeighborsClassifier(radius=1000)
model.fit(X_train_resampled, y_train_resampled)


# from sklearn.neighbors import KNeighborsClassifier

# model = KNeighborsClassifier(n_neighbors=5)
# model.fit(X_train_pca, y_train_resampled)

RadiusNeighborsClassifier(radius=1000)

#### Memprediksi hasil klasifikasi

In [53]:
y_pred = model.predict(X_test)

#### Evaluasi Model menggunakan Confusion Matrix

In [54]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[105   0   0   0]
 [ 91   0   0   0]
 [ 92   0   0   0]
 [112   0   0   0]]


##### Evaluasi Model menggunakan metrik lainnya (MAE, MSE, RMSE, MAPE)

In [55]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, mean_absolute_percentage_error

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = mean_squared_error(y_test, y_pred, squared=False)
mape = mean_absolute_percentage_error(y_test, y_pred)

print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("MAPE:", mape)

MAE: 1.5275
MSE: 3.6675
RMSE: 1.9150718002205558
MAPE: 0.7375


#### Melihat akurasi

In [56]:
#Check Akurasi
accuracy = accuracy_score(y_test, y_pred)
print("Akurasi:", accuracy)

Akurasi: 0.2625


## Menyimpan model yang telah dilatih

In [57]:
import joblib
joblib.dump(model, 'knn_model.pkl')

['knn_model.pkl']