## DataSet Information 

Dimasalah ini kamu tidak perlu memprediksi harga aktualnya tetapi indicator rentang harganya.

##### Ini adalah masalah standart Superviced Classification. Sebuah masalah dimana kita harus memprediksi rentang harga dari mobile dari 0 (low cost), 1(medium), 2(high), 3(very high)


#### Dibawah ini adalah atribut datasetnya beserta deskripsinya
| Column | Description |
| --- | --- |
| battery_power |  Total energy a battery can store in one time measured in mAh |
| blue |  Has bluetooth or not |
| clock_speed |  speed at which microprocessor executes instructions |
| dual_sim |  Has dual sim support or not |
| fc |  Front Camera mega pixels |
| four_g |  Has 4G or not |
| int_memory |  Internal Memory in Gigabytes |
| m_dep |  Mobile Depth in cm |
| mobile_wt |  Weight of mobile phone |
| n_cores |  Number of cores of processor |
| pc |  Primary Camera mega pixels |
| px_height |  Pixel Resolution Height |
| px_width |  Pixel Resolution Width |
| ram |  Random Access Memory in Mega Bytes |
| sc_h |  Screen Height of mobile in cm |
| sc_w |  Screen Width of mobile in cm |
| talk_time |  longest time that a single battery charge will last when you are |
| three_g |  Has 3G or not |
| touch_screen |  Has touch screen or not |
| wifi |  Has wifi or not |
| price_range |  This is the target variable with value of 0(low cost), 1(medium cost), 2(high cost) and 3(very high cost).|
     
     Sumber dataset ini adalah Kaggle.com.
   
  Source : https://www.kaggle.com/iabhishekofficial/mobile-price-classification?select=train.csv



## Preprocessing

#### Import Library & Memuat dataset

In [12]:
# Mengimpor pustaka yang diperlukan
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from imblearn.over_sampling import RandomOverSampler
from sklearn.decomposition import PCA
from sklearn.neighbors import RadiusNeighborsClassifier
from sklearn.metrics import accuracy_score

#Load dataset
df = pd.read_csv('train.csv')




#### Memilih fitur

In [13]:
X = df.drop(['price_range'], axis=1) 
y = df['price_range']

#### Menangani Missing Value

In [14]:
missing_values = df.isnull().sum()
print(missing_values)

battery_power    0
blue             0
clock_speed      0
dual_sim         0
fc               0
four_g           0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
three_g          0
touch_screen     0
wifi             0
price_range      0
dtype: int64


#### Menghapus Data yang tidak relevan

#### Mengubah Data kategorikal menjadi numerik

In [15]:
label_encoder = LabelEncoder()
for column in X.columns:
    if X[column].dtype == 'object':
        X[column] = label_encoder.fit_transform(X[column])

#### Menormalisasi atau mengubah skala data

In [16]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

#### Memisihakan Data menjadi set pelatihan dan pengujian

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#### Menangani data yang tidak seimbang (oversampling)

In [18]:
ros = RandomOverSampler(random_state=50)
X_train_resampled, y_train_resampled = ros.fit_resample(X_train, y_train)

## Evaluasi Model

#### Inisialisasi dan melatih model

In [20]:
model = RadiusNeighborsClassifier(radius=450)
model.fit(X, y)


RadiusNeighborsClassifier(radius=450)

#### Memprediksi hasil klasifikasi

In [21]:
y_pred = model.predict(X_test)

#### Evaluasi Model menggunakan Confusion Matrix

In [22]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[104   1   0   0]
 [  2  88   1   0]
 [  0   4  87   1]
 [  0   0   5 107]]


#### Melihat akurasi

In [24]:
#Check Akurasi
accuracy = accuracy_score(y_test, y_pred)
print("Akurasi:", accuracy)

Akurasi: 0.965


## Menyimpan model yang telah dilatih

In [25]:
import joblib
joblib.dump(model, 'knn_model.pkl')

['knn_model.pkl']